
import { BusinessEntity, BudgetCategory, SavingsGoal, Investment, Account, Transaction } from './types';
import {
  Wallet, Laptop, TrendingUp, Gift, Home, Crown, Clock, GraduationCap, RefreshCcw, Percent, Tag,
  Zap, ShoppingBasket, Utensils, Bus, Fuel, ShoppingBag, Film, Plane, Stethoscope, Package, Megaphone,
  Trophy, Landmark, Car, Umbrella, Repeat, Heart, Music, BookOpen, Coffee, Dumbbell, PawPrint,
  Gamepad2, Smartphone, Monitor, Wrench, Scissors, Baby
} from 'lucide-react';

// --- INITIAL DATA SEEDS ---

export const INITIAL_ACCOUNTS: Account[] = [];

export const MOCK_TRANSACTIONS: Transaction[] = []; // Cleared to prevent usage

// Categories are now loaded dynamically via Context / DB
export const CATEGORIES: BudgetCategory[] = [];


// --- TRANSLATIONS ---
export const TRANSLATIONS = {
  en: {
    common: {
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      save: 'Save',
      search: 'Search...',
      loading: 'Loading...',
      reset: 'Reset',
      apply: 'Apply',
      date: 'Date',
      amount: 'Amount',
      category: 'Category',
      transfer: 'Transfer',
      scan: 'Scan',
      actions: 'Actions',
      confirmDelete: 'Are you sure you want to delete this item?',
      all: 'All',
      back: 'Back',
      view: 'View', // Added missing key
      submit: 'Submit',
      processing: 'Processing...',
      available: 'Available',
      account: 'Account',
      last30Days: 'Last 30 Days',
      from: 'From',
      to: 'To',
      success: 'Success',
      error: 'Error',
      email: 'Email',
      password: 'Password',
      fullName: 'Full Name',
      frequencies: {
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
        yearly: 'Yearly'
      }
    },
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      haveAccount: 'Already have an account?',
      noAccount: "Don't have an account?",
      signInTitle: 'Welcome back',
      signUpTitle: 'Create your account',
      signInDesc: 'Enter your credentials to access your wealth dashboard.',
      signUpDesc: 'Join the exclusive wealth management platform.',
      passPlaceholder: '••••••••',
      biometricSignIn: 'Sign in with Biometrics',
    },
    nav: {
      dashboard: 'Dashboard',
      accounts: 'Accounts',
      history: 'History',
      budget: 'Budget & Goals',
      business: 'Business Hub',
      investments: 'Investments',
      reports: 'Reports',
      settings: 'Settings',
      newTransaction: 'New Transaction',
      scanr: 'Scan Receipt',
      subtitle: 'Wealth Defined',
    },
    concierge: {
      foundTransactions: 'Found {count} transactions matching your criteria.',
      searching: 'Searching transactions...',
      noResults: 'No transactions found matching your criteria.',
      welcomeAttributes: 'Welcome to AurumWolf Concierge. Text me or tap the headphones for a voice call.',
      contextBusiness: 'I see you are in the Business Hub. Would you like a P&L analysis or entity performance review?',
      contextBudget: 'Reviewing your financial plan. You have some budget categories nearing their limit.',
      contextAssets: 'Asset allocation mode active. I can assist with rebalancing strategies.',
      contextPortfolio: 'Portfolio mode active. I can analyze your active vs. passive strategy positions.',
      contextScan: 'Receipt scanner active. I will auto-extract data from any image you upload.',
      contextGeneral: 'I have your full financial context. How may I assist you today?',
      micErrorDenied: 'Microphone access denied. Please allow microphone permissions in your browser settings to use Voice Mode.',
      micErrorNotFound: 'No microphone found. Please check your audio input device.',
      micErrorUnknown: 'Voice Error',
      addedVia: 'Added via Concierge',
      transactionRecorded: 'Transaction recorded: {name} for {amount}.',
      budgetCreated: 'Budget created: {category} with limit {limit}.',
      processed: 'I processed that request.',
      connectionError: 'Connection error.',
      online: 'Online',
      connecting: 'Connecting...',
      listening: 'Listening...',
      speaking: 'Speaking...',
      voicePrompt: 'Ask me to add transactions, analyze spending, or check your budget.',
      endCall: 'End Call',
      startCall: 'Start Voice Call',
      typeMessage: 'Type a message...',
    },
    titles: {
      dashboard: 'Dashboard',
      transactionHistory: 'Transaction History',
      receiptScanner: 'Receipt Scanner',
      businessHub: 'Business Hub',
      preferences: 'Preferences',
      accountsAssets: 'Accounts & Assets',
      financialPlan: 'Financial Plan',
      investmentPortfolio: 'Investment Portfolio',
      reports: 'Financial Reports',
      welcome: 'Welcome back',
    },
    dashboard: {
      netWorth: 'Net Worth',
      welcomeBack: 'Welcome back',
      flow: 'Cash Flow',
      vsLastMonth: 'vs last month',
      assets: 'Assets',
      businessPulse: 'Business Pulse',
      spendingFlow: 'Spending Flow',
      allocation: 'Allocation',
      wealthAi: 'Wealth AI',
      analyze: 'Analyze Portfolio',
      recentActivity: 'Recent Activity',
      analyzing: 'Analyzing Assets...',
      noTransactions: 'No recent transactions',
      aiInsight: 'AI Insight',
      aurumScore: 'Aurum Score',
      finHealthIndex: 'Financial Health Index',
      healthExcellent: 'Excellent. Your portfolio is well-diversified and liquid.',
      healthGood: 'Good. Consider reducing debt to improve score.',

      healthPoor: 'Attention needed. Review high-interest liabilities.',
      thisMonth: 'This Month',
      safeToSpend: 'Safe to Spend',
      consumed: 'Consumed',
      overBudget: 'Over Budget',
      onTrack: 'On Track',
      quickActions: 'Quick Actions',
      savingsRadar: 'Savings Radar Active',
      upcoming: 'Upcoming',
      viewAll: 'View All',
      autoPay: 'Auto-Pay',
      payNow: 'Pay Now',
      noBills: 'No upcoming bills.',
      more: 'more',
      less: 'less',
      currency: 'Currency Converter',
      scoreDetail: {
        title: 'Aurum Score Breakdown',
        description: 'A comprehensive measure of your financial hygiene.',
        liquidity: 'Liquidity Ratio',
        liquidityDesc: 'Cash / Monthly Expenses',
        savings: 'Savings Rate',
        savingsDesc: 'Net Cash Flow / Income',
        debt: 'Debt-to-Asset',
        debtDesc: 'Total Debt / Total Assets',
        diversity: 'Diversity',
        diversityDesc: 'Asset Class Spread',
        pending: 'Pending Data',
        pendingDesc: 'Add income and assets to generate score.',
        excellent: 'Elite Financial Status',
        good: 'Solid Foundation',
        fair: 'Needs Optimization',
        poor: 'Critical Attention Needed'
      },
    },
    transactions: {
      income: 'Income',
      expense: 'Expense',
      recurring: 'Subscriptions',
      filters: 'Filters',
      clearFilters: 'Clear Filters',
      found: 'Transactions Found',
      export: 'Export Visible',
      stopSubscription: 'Stop Subscription',
      nextDue: 'Next Due',
      dailySummary: 'Daily Summary',
      type: 'Type',
      status: 'Status',
      description: 'Description',
      frequency: 'Frequency',
      isRecurring: 'Recurring Transaction',
    },
    accounts: {
      globalNetLiquid: 'Global Net Liquid',
      addAsset: 'Add Asset',
      transferFunds: 'Transfer Funds',
      freeze: 'Freeze',
      unfreeze: 'Unfreeze',
      ledger: 'Ledger',
      balanceHistory: 'Balance History',
      quickActions: 'Quick Actions',
      available: 'Available',
      limit: 'Limit',
      apr: 'APR',
      frozen: 'Frozen',
      frozenAlert: 'This account is frozen. You cannot transfer funds.',
      dueDay: 'Due Day',
      util: 'UTIL',
      selectSource: 'Select Source...',
      selectDest: 'Select Destination...',
      flow30: '30-Day Flow',
      newAccount: 'New Account',
      editAccount: 'Edit Account',
      accountName: 'Account Name',
      accountType: 'Account Type',
      institution: 'Institution',
      initialBalance: 'Initial Balance',
      currency: 'Currency',
      color: 'Color',
      from: 'From',
      to: 'To',
      transferAmount: 'Transfer Amount',
      types: {
        checking: 'Checking',
        savings: 'Savings',
        credit: 'Credit Card',
        investment: 'Investment',
        loan: 'Loan',
        cash: 'Cash',
        crypto: 'Crypto Wallet',
        other: 'Other'
      },
      balanceAdjustment: 'Balance Adjustment',
      startingBalance: 'Starting Balance',
    },
    budget: {
      netCashFlow: 'Net Cash Flow',
      savingsRate: 'Savings Rate',
      incomeMtd: 'Income (MTD)',
      expensesMtd: 'Expenses (MTD)',
      allocations: 'Allocations',
      editStructure: 'Edit Structure',
      doneEditing: 'Done Editing',
      wealthGoals: 'Wealth Goals',
      addGoal: 'Add Goal',
      editGoal: 'Edit Goal',
      newGoal: 'New Goal',
      expenseLimits: 'Expense Limits',
      addCategory: 'Add Category',
      newCategory: 'New Category',
      incomeTargets: 'Income Targets',
      addFunds: 'Add Funds',
      confirmDeposit: 'Confirm Deposit',
      progress: 'Progress',
      remaining: 'remaining',
      targetAchieved: 'Target Achieved!',
      exceeded: 'Exceeded limit by',
      safe: 'Safely under pace by',
      alert: 'Budget Alert',
      alertMessage: 'Exceeded limit by',
      goalName: 'Goal Name',
      targetAmount: 'Target Amount',
      savedAmount: 'Saved Amount',
      deadline: 'Deadline',
      categoryName: 'Category Name',
      limitAmount: 'Limit Amount',
      contribution: 'Contribution Amount',
      // New Status Labels
      status: 'Status',
      withinBudget: 'Within Budget',
      overBudget: 'Over Budget',
      underBudget: 'Under Budget',
      targetMet: 'Target Met',
      notMet: 'Target Not Met',
      used: 'used',
      received: 'received',
      percentage: 'Percentage',
      dailySafeSpend: 'Suggested Daily Spend',
      recentTransactions: 'Impactful Transactions',
      onTrack: 'You are on track!',
      attention: 'Attention needed',
      adviceSafe: 'To stay safely within budget, limit your daily spend to:',
      adviceOver: 'You have exceeded your limit. Review your recent transactions to adjust.',
      incomeHigher: 'higher than expected',
      incomeLower: 'lower than expected',
      majorContributor: 'Largest Transaction',
      drivenBy: 'Driven by',
    },
    business: {
      executiveOverview: 'Executive Overview',
      realTimePerf: 'Real-time consolidated performance.',
      totalRevenue: 'Total Revenue',
      netProfit: 'Net Profit',
      avgMargin: 'Avg Margin',
      headcount: 'Total Headcount',
      venturesPerf: 'Ventures Performance',
      corpStructure: 'Corporate Structure',
      addEntity: 'Add Entity',
      registerEntity: 'Register New Entity',
      editEntity: 'Edit Entity',
      revenue: 'Revenue',
      profit: 'Profit',
      expenses: 'Expenses',
      margin: 'Margin',
      entityLedger: 'Entity Ledger',
      configureKpi: 'Configure KPI Dashboard',
      entityName: 'Entity Name',
      entityType: 'Entity Type',
      parentEntity: 'Parent Entity',
      details: 'Details',
      performance: 'Performance',
      entityNameColumn: 'Entity Name',
      selectKpiDesc: 'Select the key performance indicators relevant to this specific business model.',
      operationalMetricsEditable: 'Operational Metrics (Editable)',
      types: {
        holding: 'Holding Company',
        subsidiary: 'Subsidiary',
        store: 'Physical Store',
        channel: 'Digital Channel',
        service: 'Service Provider',
        real_estate: 'Real Estate'
      }
    },
    investments: {
      portfolioValue: 'Total Portfolio Value',
      allTimeReturn: 'All Time Return',
      passive: 'Pasivo',
      active: 'Activo',
      allocation: 'Asignación',
      addInvestment: 'Añadir Inversión',
      editInvestment: 'Editar Inversión',
      holdings: 'Holdings',
      costBasis: 'Cost Basis',
      marketPrice: 'Market Price',
      units: 'units',
      updateAsset: 'Update Asset',
      addToPortfolio: 'Add to Portfolio',
      assetName: 'Asset Name',
      ticker: 'Ticker / ID',
      quantity: 'Quantity',
      currentValue: 'Current Value',
      strategies: {
        passive: 'Passive (Long Term)',
        active: 'Active (Trading)',
        income: 'Income Generating',
        speculative: 'Speculative'
      },
      types: {
        stock: 'Stock / Equity',
        etf: 'ETF / Index Fund',
        crypto: 'Cryptocurrency',
        real_estate: 'Real Estate',
        commodity: 'Commodity',
        bond: 'Bond / Fixed Income',
        private_equity: 'Private Equity',
        cash: 'Cash / MM'
      }
    },
    reports: {
      generate: 'Generate Report',
      monthly: 'Monthly Statement',
      quarterly: 'Quarterly Review',
      annual: 'Annual Report',
      downloadPdf: 'Download PDF',
      closePreview: 'Close Preview',
      personalSummary: 'Personal Summary',
      businessPerformance: 'Business Performance',
      portfolioHealth: 'Portfolio Health',
      selectPeriod: 'Select Reporting Period',
      generatedOn: 'Generated on',
      noData: 'No data available for this report period.',
      metric: 'Metric',
      currentPeriod: 'Current Period',
      previousPeriod: 'Previous Period',
      delta: 'Delta',
      personalWealth: 'Personal Wealth',
      totalIncome: 'Total Income',
      livingExpenses: 'Living Expenses',
      netSavings: 'Net Savings',
      businessVentures: 'Business Ventures',
      grossRevenue: 'Gross Revenue',
      operationalExp: 'Operational Exp',
      netProfit: 'Net Profit',
      entityLedger: 'Entity Ledger',
      entity: 'Entity',
      revenue: 'Revenue',
      expenses: 'Expenses',
      marginPct: 'Margin %',
      generatedBy: 'Generated by AurumWolf Finance',
      confidential: 'Confidential & Proprietary',
      reference: 'Reference',
    },
    scan: {
      dragDrop: 'Drag & Drop Receipt',
      tapDrop: 'Tap to Browse or Drop Receipt',
      openCamera: 'Open Camera',
      uploadFile: 'Upload File',
      orClick: 'or click to browse',
      supports: 'Supports PNG, JPG, PDF',
      scanning: 'Scanning Receipt...',
      analyzing: 'Analyzing details with OCR...',
      scanComplete: 'Scan Complete!',
      readyToImport: 'Ready to import details.',
      review: 'Review Transaction',
      merchant: 'Merchant',
    },
    settings: {
      appPreferences: 'App Preferences',
      darkMode: 'Dark Mode',
      adjustAppearance: 'Adjust appearance',
      language: 'Language',
      interfaceLanguage: 'Interface language',
      baseCurrency: 'Global Base Currency',
      baseCurrencyDesc: 'For dashboard and net worth',
      notifications: 'Notifications',
      notificationsDesc: 'Alerts & Tips',
      security: 'Security',
      biometric: 'Biometric Authentication',
      biometricDesc: 'FaceID / TouchID',
      changePin: 'Change PIN',
      changePinDesc: 'Changed 30 days ago',
      dataSovereignty: 'Data Sovereignty',
      backup: 'System Backup (JSON)',
      backupDesc: 'Download all data',
      restore: 'Restore Backup',
      restoreDesc: 'Overwrite current data',
      exportCsv: 'Export Report (CSV)',
      exportCsvDesc: 'Excel compatible',
      factoryReset: 'Factory Reset',
      factoryResetDesc: 'Clear all local storage',
      signOut: 'Sign Out',
      editProfile: 'Edit Profile',
      premiumMember: 'Premium Member',
      earlyAccess: 'Early Access',
      alertInvalidBackup: 'Invalid backup file: Data structure does not match expected format.',
      alertRestoreWarning: 'Warning: Restoring will overwrite all current data. This action cannot be undone. Continue?',
      alertRestoreSuccess: 'Restore successful. Reloading...',
      alertParseError: 'Error parsing backup file. Please ensure it is a valid JSON.',
      alertReconcileWarning: 'This will recalculate all account balances based on their initial snapshot and transaction history. This action cannot be undone. Proceed?',
      alertReconcileSuccess: 'Balances reconciled successfully.',
      termReconcile: 'Reconcile Balances',
      termReconcileDesc: 'Recompute from transactions & initial snapshot',
    },
    transactionForm: {
      titleNew: 'New Transaction',
      titleEdit: 'Edit Transaction',
      scanReceipt: 'Scan Receipt',
      scanning: 'Scanning...',
      expense: 'Expense',
      income: 'Income',
      amount: 'Amount',
      rate: 'Rate',
      settlement: 'Settlement',
      chargeAccount: 'Charge Account',
      merchantSource: 'Merchant / Source',
      merchantPlaceholder: 'e.g. Starbucks, Uber, Salary',
      findLocation: 'Find Location & Enrich',
      locationFound: 'Location Found',
      date: 'Date',
      description: 'Description (Optional)',
      descriptionPlaceholder: 'Add notes...',
      splitTransaction: 'Split This Transaction',
      splitTitle: 'Split Transaction',
      reset: 'Reset',
      addSplit: 'Add Split',
      remaining: 'Remaining',
      over: 'Over',
      matched: 'Matched',
      recurringPayment: 'Recurring Payment',
      frequency: 'Frequency',
      endDate: 'End Date',
      businessExpense: 'Business Expense',
      assignEntity: 'Assign Entity',
      selectBusiness: 'Select Business Unit...',
      delete: 'Delete',
      cancel: 'Cancel',
      update: 'Update Transaction',
      add: 'Add Transaction',
      selectCategory: 'Category...',
      suggested: 'Suggested',
    }
  },
  es: {
    common: {
      add: 'Añadir',
      edit: 'Editar',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      save: 'Guardar',
      search: 'Buscar...',
      loading: 'Cargando...',
      reset: 'Reiniciar',
      apply: 'Aplicar',
      date: 'Fecha',
      amount: 'Monto',
      category: 'Categoría',
      transfer: 'Transferir',
      scan: 'Escanear',
      actions: 'Acciones',
      confirmDelete: '¿Estás seguro de que deseas eliminar este elemento?',
      all: 'Todos',
      back: 'Volver',
      view: 'Ver', // Added missing key
      submit: 'Enviar',
      processing: 'Procesando...',
      available: 'Disponible',
      account: 'Cuenta',
      last30Days: 'Últimos 30 Días',
      from: 'Desde',
      to: 'Para',
      success: 'Éxito',
      error: 'Error',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      fullName: 'Nombre Completo',
      frequencies: {
        daily: 'Diario',
        weekly: 'Semanal',
        monthly: 'Mensual',
        yearly: 'Anual'
      }
    },
    auth: {
      signIn: 'Iniciar Sesión',
      signUp: 'Registrarse',
      haveAccount: '¿Ya tienes una cuenta?',
      noAccount: '¿No tienes una cuenta?',
      signInTitle: 'Bienvenido de nuevo',
      signUpTitle: 'Crea tu cuenta',
      signInDesc: 'Ingresa tus credenciales para acceder a tu tablero.',
      signUpDesc: 'Únete a la plataforma exclusiva de gestión patrimonial.',
      passPlaceholder: '••••••••',
      biometricSignIn: 'Iniciar con Biometría',
    },
    nav: {
      dashboard: 'Tablero',
      accounts: 'Cuentas',
      history: 'Historial',
      budget: 'Presupuesto',
      business: 'Negocios',
      investments: 'Inversiones',
      reports: 'Reportes',
      settings: 'Ajustes',
      newTransaction: 'Nueva Transacción',
      scanr: 'Escanear Recibo',
      subtitle: 'Riqueza Definida',
    },
    concierge: {
      foundTransactions: 'Encontradas {count} transacciones que coinciden con tu criterio.',
      searching: 'Buscando transacciones...',
      noResults: 'No se encontraron transacciones que coincidan con tu criterio.',
      welcomeAttributes: 'Bienvenido a AurumWolf Concierge. Envíame un mensaje de texto o toca los auriculares para una llamada de voz.',
      contextBusiness: 'Veo que estás en el Centro de Negocios. ¿Te gustaría un análisis de PyG o una revisión del rendimiento de la entidad?',
      contextBudget: 'Revisando tu plan financiero. Tienes algunas categorías de presupuesto cerca de su límite.',
      contextAssets: 'Modo de asignación de activos activo. Puedo ayudar con estrategias de rebalanceo.',
      contextPortfolio: 'Modo de portafolio activo. Puedo analizar tus posiciones de estrategia activa vs. pasiva.',
      contextScan: 'Escáner de recibos activo. Extraeré automáticamente los datos de cualquier imagen que subas.',
      contextGeneral: 'Tengo tu contexto financiero completo. ¿Cómo puedo ayudarte hoy?',
      micErrorDenied: 'Acceso al micrófono denegado. Por favor, permite el acceso al micrófono en la configuración de tu navegador para usar el Modo de Voz.',
      micErrorNotFound: 'No se encontró micrófono. Por favor, verifica tu dispositivo de entrada de audio.',
      micErrorUnknown: 'Error de Voz',
      addedVia: 'Añadido vía Concierge',
      transactionRecorded: 'Transacción registrada: {name} por {amount}.',
      budgetCreated: 'Presupuesto creado: {category} con límite {limit}.',
      processed: 'Procesé esa solicitud.',
      connectionError: 'Error de conexión.',
      online: 'En línea',
      connecting: 'Conectando...',
      listening: 'Escuchando...',
      speaking: 'Hablando...',
      voicePrompt: 'Pídeme añadir transacciones, analizar gastos o revisar tu presupuesto.',
      endCall: 'Finalizar Llamada',
      startCall: 'Iniciar Llamada de Voz',
      typeMessage: 'Escribe un mensaje...',
    },
    titles: {
      dashboard: 'Tablero Principal',
      transactionHistory: 'Historial de Transacciones',
      receiptScanner: 'Escáner de Recibos',
      businessHub: 'Centro de Negocios',
      preferences: 'Preferencias',
      accountsAssets: 'Cuentas y Activos',
      financialPlan: 'Plan Financiero',
      investmentPortfolio: 'Portafolio de Inversión',
      reports: 'Reportes Financieros',
      welcome: 'Bienvenido de nuevo',
    },
    dashboard: {
      netWorth: 'Patrimonio Neto',
      welcomeBack: 'Bienvenido de nuevo',
      flow: 'Flujo de caja',
      vsLastMonth: 'vs mes anterior',
      assets: 'Activos',
      businessPulse: 'Pulso de Negocios',
      spendingFlow: 'Flujo de Gastos',
      allocation: 'Asignación',
      wealthAi: 'IA Financiera',
      analyze: 'Analizar Portafolio',
      recentActivity: 'Actividad Reciente',
      analyzing: 'Analizando Activos...',
      noTransactions: 'Sin transacciones recientes',
      aiInsight: 'Insight de IA',
      aurumScore: 'Puntuación Aurum',
      finHealthIndex: 'Índice de Salud Financiera',
      healthExcellent: 'Excelente. Tu portafolio está bien diversificado y líquido.',
      healthGood: 'Bueno. Considera reducir deudas para mejorar tu puntuación.',

      healthPoor: 'Atención requerida. Revisa pasivos de alto interés.',
      thisMonth: 'Este Mes',
      safeToSpend: 'Disponible para Gastar',
      consumed: 'Consumido',
      overBudget: 'Excedido',
      onTrack: 'En camino',
      quickActions: 'Acciones Rápidas',
      savingsRadar: 'Radar de Ahorro Activo',
      upcoming: 'Próximos',
      viewAll: 'Ver Todo',
      autoPay: 'Pago Automático',
      payNow: 'Pagar Ahora',
      noBills: 'Sin facturas próximas.',
      more: 'más',
      less: 'menos',
      currency: 'Conversor Divisas',
      scoreDetail: {
        title: 'Desglose Aurum Score',
        description: 'Una medida integral de tu higiene financiera.',
        liquidity: 'Ratio de Liquidez',
        liquidityDesc: 'Efectivo / Gastos Mensuales',
        savings: 'Tasa de Ahorro',
        savingsDesc: 'Flujo Neto / Ingresos',
        debt: 'Deuda-Activo',
        debtDesc: 'Deuda Total / Activos Totales',
        diversity: 'Diversificación',
        diversityDesc: 'Variedad de Activos',
        pending: 'Datos Pendientes',
        pendingDesc: 'Añade ingresos y activos para generar tu score.',
        excellent: 'Estatus Financiero de Élite',
        good: 'Fundación Sólida',
        fair: 'Necesita Optimización',
        poor: 'Atención Crítica Necesaria'
      },
    },
    transactions: {
      income: 'Ingresos',
      expense: 'Gastos',
      recurring: 'Suscripciones',
      filters: 'Filtros',
      clearFilters: 'Limpiar Filtros',
      found: 'Transacciones Encontradas',
      export: 'Exportar Visible',
      stopSubscription: 'Cancelar Suscripción',
      nextDue: 'Próximo Vencimiento',
      dailySummary: 'Resumen Diario',
      type: 'Tipo',
      status: 'Estado',
      description: 'Descripción',
      frequency: 'Frecuencia',
      isRecurring: 'Transacción Recurrente',
    },
    accounts: {
      globalNetLiquid: 'Liquidez Global Neta',
      addAsset: 'Añadir Activo',
      transferFunds: 'Transferir Fondos',
      freeze: 'Congelar',
      unfreeze: 'Descongelar',
      ledger: 'Libro Mayor',
      balanceHistory: 'Historial de Balance',
      quickActions: 'Acciones Rápidas',
      available: 'Disponible',
      limit: 'Límite',
      utilization: 'Uso',
      frozenAlert: 'Esta cuenta está congelada. Descongélala para transferir fondos.',
      newAccount: 'Nueva Cuenta',
      editAccount: 'Editar Cuenta',
      accountName: 'Nombre de Cuenta',
      accountType: 'Tipo de Cuenta',
      institution: 'Institución',
      initialBalance: 'Balance Inicial',
      currency: 'Moneda',
      color: 'Color',
      from: 'Desde',
      to: 'Para',
      transferAmount: 'Monto de Transferencia',
      types: {
        checking: 'Cuenta Corriente',
        savings: 'Ahorros',
        credit: 'Tarjeta de Crédito',
        investment: 'Inversión',
        loan: 'Préstamo',
        cash: 'Efectivo',
        crypto: 'Crypto Wallet',
        other: 'Otro'
      },
      balanceAdjustment: 'Ajuste de Balance',
      startingBalance: 'Balance Inicial',
    },
    budget: {
      netCashFlow: 'Flujo de Caja Neto',
      savingsRate: 'Tasa de Ahorro',
      incomeMtd: 'Ingresos Mes',
      expensesMtd: 'Gastos Mes',
      allocations: 'Asignaciones',
      editStructure: 'Editar Estructura',
      doneEditing: 'Edición Terminada',
      wealthGoals: 'Metas de Riqueza',
      addGoal: 'Añadir Meta',
      editGoal: 'Editar Meta',
      newGoal: 'Nueva Meta',
      expenseLimits: 'Límites de Gastos',
      addCategory: 'Añadir Categoría',
      newCategory: 'Nueva Categoría',
      incomeTargets: 'Objetivos de Ingresos',
      addFunds: 'Agregar Fondos',
      confirmDeposit: 'Confirmar Depósito',
      progress: 'Progreso',
      remaining: 'Restante',
      targetAchieved: 'Objetivo Logrado',
      exceeded: 'Excedido por',
      safe: 'Seguro por',
      alert: 'Alerta de Presupuesto',
      alertMessage: 'Límite excedido por',
      goalName: 'Nombre de Meta',
      targetAmount: 'Monto Objetivo',
      savedAmount: 'Monto Ahorrado',
      deadline: 'Fecha Límite',
      noDeadline: 'Sin Fecha Límite',
      due: 'Vence',
      categoryName: 'Nombre Categoría',
      limitAmount: 'Monto Límite',
      contribution: 'Monto a Contribuir',
      // New Status Labels
      status: 'Estado',
      withinBudget: 'Dentro del Presupuesto',
      overBudget: 'Sobrepasado',
      underBudget: 'Por debajo',
      targetMet: 'Meta Alcanzada',
      notMet: 'Meta No Alcanzada',
      used: 'usado',
      received: 'recibido',
      percentage: 'Porcentaje',
      dailySafeSpend: 'Gasto Diario Sugerido',
      recentTransactions: 'Transacciones Recientes',
      onTrack: '¡Vas por buen camino!',
      attention: 'Atención requerida',
      adviceSafe: 'Para mantenerte seguro, intenta gastar como máximo:',
      adviceOver: 'Has excedido el límite. Revisa tus gastos recientes para ajustar.',
      incomeHigher: 'mayor a lo esperado',
      incomeLower: 'menor a lo esperado',
      majorContributor: 'Transacción Mayor',
      drivenBy: 'Impulsado por',
    },
    business: {
      executiveOverview: 'Resumen Ejecutivo',
      structure: 'Estructura Corporativa',
      entity: 'Entidad Comercial',
      taxId: 'ID Fiscal',
      kpi: 'Panel de KPI',
      realTimePerf: 'Rendimiento consolidado en tiempo real.',
      totalRevenue: 'Ingresos Totales',
      netProfit: 'Beneficio Neto',
      avgMargin: 'Margen Prom.',
      headcount: 'Personal Total',
      venturesPerf: 'Rendimiento de Empresas',
      corpStructure: 'Estructura Corporativa',
      addEntity: 'Añadir Entidad',
      registerEntity: 'Registrar Nueva Entidad',
      editEntity: 'Editar Entidad',
      revenue: 'Ingresos',
      profit: 'Ganancia',
      expenses: 'Gastos',
      margin: 'Margen',
      entityLedger: 'Libro Mayor de Entidad',
      configureKpi: 'Configurar Tablero KPI',
      entityName: 'Nombre de Entidad',
      entityType: 'Tipo de Entidad',
      parentEntity: 'Entidad Madre',
      details: 'Detalles',
      performance: 'Rendimiento',
      entityNameColumn: 'Nombre de Entidad',
      selectKpiDesc: 'Seleccione los indicadores clave de rendimiento relevantes para este modelo de negocio.',
      operationalMetricsEditable: 'Métricas Operativas (Editables)',
      types: {
        holding: 'Holding',
        subsidiary: 'Subsidiaria',
        store: 'Tienda Física',
        channel: 'Canal Digital',
        service: 'Proveedor de Servicios',
        real_estate: 'Bienes Raíces'
      }
    },
    investments: {
      portfolioValue: 'Valor Total del Portafolio',
      allTimeReturn: 'Retorno Total',
      passive: 'Pasivo',
      active: 'Activo',
      allocation: 'Asignación',
      addInvestment: 'Añadir Inversión',
      editInvestment: 'Editar Inversión',
      holdings: 'Tenencias',
      costBasis: 'Base de Costo',
      marketPrice: 'Precio de Mercado',
      units: 'unidades',
      updateAsset: 'Actualizar Activo',
      addToPortfolio: 'Añadir al Portafolio',
      assetName: 'Nombre del Activo',
      ticker: 'Ticker / ID',
      quantity: 'Cantidad',
      currentValue: 'Valor Actual',
      value: 'Valor',
      priceHistory: 'Historial de Precios',
      deleteConfirm: '¿Estás seguro de que quieres eliminar este activo?',
      high: 'Alto',
      low: 'Bajo',
      assetNamePlaceholder: 'Nombre del Activo (ej. Apple Inc)',
      tickerPlaceholder: 'Ticker (ej. AAPL)',
      avgBuyPrice: 'Precio Compra Prom.',
      currentPrice: 'Precio Actual',
      currency: 'Moneda',
      strategies: {
        passive: 'Pasiva (Largo Plazo)',
        active: 'Activa (Trading)',
        income: 'Generación de Rentas',
        speculative: 'Especulativa'
      },
      types: {
        stock: 'Acción / Equity',
        etf: 'ETF / Fondo Indexado',
        crypto: 'Criptomoneda',
        real_estate: 'Bienes Raíces',
        commodity: 'Commodity',
        bond: 'Bono / Renta Fija',
        private_equity: 'Private Equity',
        cash: 'Efectivo / MM'
      }
    },
    reports: {
      generate: 'Generar Reporte',
      monthly: 'Estado Mensual',
      quarterly: 'Revisión Trimestral',
      annual: 'Informe Anual',
      downloadPdf: 'Descargar PDF',
      closePreview: 'Cerrar Vista Previa',
      personalSummary: 'Resumen Personal',
      businessPerformance: 'Rendimiento Comercial',
      portfolioHealth: 'Salud del Portafolio',
      selectPeriod: 'Seleccionar Periodo',
      generatedOn: 'Generado el',
      noData: 'No hay datos disponibles para este periodo.',
    },
    scan: {
      dragDrop: 'Arrastra y suelta tu recibo',
      orClick: 'o haz clic para buscar',
      supports: 'Soporta PNG, JPG, PDF',
      scanning: 'Escaneando Recibo...',
      analyzing: 'Analizando detalles con OCR...',
      scanComplete: '¡Escaneo Completo!',
      readyToImport: 'Listo para importar detalles.',
      review: 'Revisar Transacción',
      merchant: 'Comercio / Vendedor',
    },
    settings: {
      appPreferences: 'Preferencias de la App',
      darkMode: 'Modo Oscuro',
      adjustAppearance: 'Ajustar apariencia',
      language: 'Idioma / Language',
      interfaceLanguage: 'Idioma de la interfaz',
      baseCurrency: 'Moneda Base Global',
      baseCurrencyDesc: 'Para el tablero y valor neto',
      notifications: 'Notificaciones',
      notificationsDesc: 'Alertas y Consejos',
      security: 'Seguridad',
      biometric: 'Autenticación Biométrica',
      biometricDesc: 'FaceID / TouchID',
      changePin: 'Cambiar PIN',
      changePinDesc: 'Cambiado hace 30 días',
      dataSovereignty: 'Soberanía de Datos',
      backup: 'Respaldo del Sistema (JSON)',
      backupDesc: 'Descargar todos los datos',
      restore: 'Restaurar Copia',
      restoreDesc: 'Sobrescribir datos actuales',
      exportCsv: 'Exportar Reporte (CSV)',
      exportCsvDesc: 'Compatible con Excel',
      factoryReset: 'Restablecimiento de Fábrica',
      factoryResetDesc: 'Borrar todo el almacenamiento local',
      signOut: 'Cerrar Sesión',
      editProfile: 'Editar Perfil',
      premiumMember: 'Miembro Premium',
      earlyAccess: 'Acceso Anticipado',
      alertInvalidBackup: 'Archivo de respaldo inválido: La estructura de datos no coincide con el formato esperado.',
      alertRestoreWarning: 'Advertencia: La restauración sobrescribirá todos los datos actuales. Esta acción no se puede deshacer. ¿Continuar?',
      alertRestoreSuccess: 'Restauración exitosa. Recargando...',
      alertParseError: 'Error al analizar el archivo de respaldo. Asegúrese de que sea un JSON válido.',
      alertReconcileWarning: 'Esto recalculará todos los saldos de cuenta basándose en su instantánea inicial y el historial de transacciones. Esta acción no se puede deshacer. ¿Proceder?',
      alertReconcileSuccess: 'Saldos conciliados exitosamente.',
      termReconcile: 'Conciliar Saldos',
      termReconcileDesc: 'Recalcular desde transacciones e instantánea inicial',
    },
    transactionForm: {
      titleNew: 'Nueva Transacción',
      titleEdit: 'Editar Transacción',
      scanReceipt: 'Escanear Recibo',
      scanning: 'Escaneando...',
      expense: 'Gasto',
      income: 'Ingreso',
      amount: 'Monto',
      rate: 'Tasa',
      settlement: 'Liquidación',
      chargeAccount: 'Cuenta de Cargo',
      merchantSource: 'Comercio / Fuente',
      merchantPlaceholder: 'ej. Starbucks, Uber, Salario',
      findLocation: 'Buscar Ubicación y Enriquecer',
      locationFound: 'Ubicación Encontrada',
      date: 'Fecha',
      description: 'Descripción (Opcional)',
      descriptionPlaceholder: 'Añadir notas...',
      splitTransaction: 'Dividir esta Transacción',
      splitTitle: 'Transacción Dividida',
      reset: 'Reiniciar',
      addSplit: 'Añadir División',
      remaining: 'Restante',
      over: 'Excedido',
      matched: 'Coincide',
      recurringPayment: 'Pago Recurrente',
      frequency: 'Frecuencia',
      endDate: 'Fecha Final',
      businessExpense: 'Gasto de Negocio',
      assignEntity: 'Asignar Entidad',
      selectBusiness: 'Seleccionar Unidad de Negocio...',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      update: 'Actualizar Transacción',
      add: 'Añadir Transacción',
      selectCategory: 'Categoría...',
      suggested: 'Sugerido',
    }
  }
};

// --- CURRENCY & FX RATES ---
export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' },
  { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-DE' },
  { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', locale: 'ja-JP' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso', locale: 'es-MX' },
  { code: 'BTC', symbol: '₿', name: 'Bitcoin', locale: 'en-US' },
];

// Base USD Rates
export const FX_RATES: Record<string, number> = {
  'USD': 1.0,
  'EUR': 0.92, // 1 USD = 0.92 EUR
  'GBP': 0.79, // 1 USD = 0.79 GBP
  'JPY': 149.50, // 1 USD = 149.50 JPY
  'MXN': 17.50, // 1 USD = ~17.50 MXN
  'BTC': 0.000015, // 1 USD = ~0.000015 BTC (Simulated)
};

// --- CATEGORY DEFINITIONS ---


// --- BUDGET MAPPING ---
export const BUDGET_MAPPING: Record<string, string[]> = {
  'Housing & Utilities': ['Rent / Mortgage', 'Utilities'],
  'Food & Dining': ['Groceries', 'Dining Out', 'Restaurants', 'Coffee'],
  'Shopping': ['Shopping', 'Clothing', 'Electronics', 'Apple Store'],
  'Travel': ['Travel', 'Transport', 'Fuel', 'Uber Premium', 'Airlines'],
  'Entertainment': ['Entertainment', 'Movies', 'Events'],
  'Subscriptions': ['Netflix', 'Spotify', 'Hulu', 'Adobe', 'Service Subscription', 'Apple Services'],
  // Income
  'Salary / Wages': ['Salary', 'Wages', 'Paycheck'],
  'Freelance / Contract': ['Freelance', 'Contract', 'Consulting Fee'],
};

// --- BUSINESS HIERARCHY ---
export const BUSINESS_ENTITIES: BusinessEntity[] = [
  // Tier 1: Holding
  { id: 'prelude_holdings', name: 'Prelude Holdings LLC', type: 'subsidiary' },

  // Tier 2: Subsidiaries / Regional HQs
  { id: 'hq_nyc', name: 'Prelude Retail North America', type: 'store', parent_id: 'prelude_holdings', customMetricsConfig: ['footfall', 'conversion'] },
  { id: 'hq_emea', name: 'Prelude EMEA Operations', type: 'subsidiary', parent_id: 'prelude_holdings' },

  // Tier 3: Physical Stores
  { id: 'store_nyc', name: 'Manhattan Flagship', type: 'store', parent_id: 'hq_nyc', customMetricsConfig: ['footfall', 'conversion', 'avg_basket'] },
  { id: 'store_ldn', name: 'London Oxford St', type: 'store', parent_id: 'hq_emea' },
  { id: 'store_dxb', name: 'Dubai Mall Boutique', type: 'store', parent_id: 'hq_emea' },
  { id: 'pop_tokyo', name: 'Tokyo Shibuya Pop-up', type: 'store', parent_id: 'prelude_holdings' },

  // Tier 3: Digital Channels
  { id: 'online_global', name: 'Global E-Commerce', type: 'channel', parent_id: 'prelude_holdings', customMetricsConfig: ['cac', 'churn', 'sessions'] },
  { id: 'wholesale', name: 'Wholesale / B2B', type: 'channel', parent_id: 'hq_nyc' },
  { id: 'app_ios', name: 'iOS App Store', type: 'channel', parent_id: 'online_global' },
];

// --- BUSINESS METRIC TEMPLATES ---
// These are suggestions available to the user when configuring a business entity
export const METRIC_TEMPLATES = [
  // Retail / Physical Store
  { id: 'footfall', name: 'Monthly Footfall', type: 'number', category: 'store' },
  { id: 'conversion', name: 'Conversion Rate', type: 'percentage', category: 'store' },
  { id: 'avg_basket', name: 'Avg Basket Size', type: 'currency', category: 'store' },
  { id: 'shrinkage', name: 'Inventory Shrinkage', type: 'percentage', category: 'store' },

  // E-Commerce / Digital
  { id: 'cac', name: 'Cust. Acquisition Cost (CAC)', type: 'currency', category: 'channel' },
  { id: 'churn', name: 'Churn Rate', type: 'percentage', category: 'channel' },
  { id: 'sessions', name: 'Monthly Sessions', type: 'number', category: 'channel' },
  { id: 'aov', name: 'Avg Order Value', type: 'currency', category: 'channel' },
  { id: 'roas', name: 'ROAS', type: 'number', category: 'channel' },

  // Real Estate
  { id: 'occupancy', name: 'Occupancy Rate', type: 'percentage', category: 'real_estate' },
  { id: 'yield', name: 'Rental Yield', type: 'percentage', category: 'real_estate' },
  { id: 'maintenance', name: 'Maintenance Cost', type: 'currency', category: 'real_estate' },

  // Service / Agency
  { id: 'billable', name: 'Billable Hours', type: 'number', category: 'service' },
  { id: 'pipeline', name: 'Pipeline Value', type: 'currency', category: 'service' },
  { id: 'nps', name: 'Net Promoter Score', type: 'number', category: 'service' },
];

// --- ICON MAP ---
export const ICON_MAP: Record<string, any> = {
  wallet: Wallet,
  laptop: Laptop,
  trendingUp: TrendingUp,
  gift: Gift,
  home: Home,
  crown: Crown,
  clock: Clock,
  graduationCap: GraduationCap,
  refreshCcw: RefreshCcw,
  percent: Percent,
  tag: Tag,
  zap: Zap,
  shoppingBasket: ShoppingBasket,
  utensils: Utensils,
  bus: Bus,
  fuel: Fuel,
  shoppingBag: ShoppingBag,
  film: Film,
  plane: Plane,
  stethoscope: Stethoscope,
  package: Package,
  megaphone: Megaphone,
  trophy: Trophy,
  landmark: Landmark,
  car: Car,
  umbrella: Umbrella
};

// --- INITIAL BUDGET CONFIG ---
export const INITIAL_BUDGET_CONFIG: BudgetCategory[] = [
  // Income Targets
  { id: 'inc_1', category: 'Salary / Wages', limit: 8000, spent: 0, color: 'bg-emerald-500', icon_key: 'wallet', type: 'income' },
  { id: 'inc_2', category: 'Freelance / Contract', limit: 4000, spent: 0, color: 'bg-teal-500', icon_key: 'laptop', type: 'income' },

  // Expense Limits
  { id: '1', category: 'Housing & Utilities', limit: 3500, spent: 0, color: 'bg-purple-500', icon_key: 'home', type: 'expense' },
  { id: '2', category: 'Food & Dining', limit: 1200, spent: 0, color: 'bg-orange-500', icon_key: 'utensils', type: 'expense' },
  { id: '3', category: 'Shopping', limit: 1000, spent: 0, color: 'bg-pink-500', icon_key: 'shoppingBag', type: 'expense' },
  { id: '4', category: 'Travel', limit: 2000, spent: 0, color: 'bg-blue-500', icon_key: 'plane', type: 'expense' },
  { id: '5', category: 'Entertainment', limit: 500, spent: 0, color: 'bg-green-500', icon_key: 'zap', type: 'expense' },
];

// --- INITIAL SAVINGS GOALS ---
export const INITIAL_GOALS: SavingsGoal[] = [
  { id: 'g1', name: 'Emergency Fund', targetAmount: 50000, savedAmount: 15000, color: 'bg-emerald-500', icon: Umbrella, deadline: '2024-12-31' },
  { id: 'g2', name: 'Porsche 911 GT3', targetAmount: 220000, savedAmount: 45000, color: 'bg-gold-500', icon: Car, deadline: '2025-06-30' },
  { id: 'g3', name: 'Aspen Real Estate', targetAmount: 1500000, savedAmount: 350000, color: 'bg-blue-500', icon: Landmark, deadline: '2026-01-01' },
];

// --- INITIAL INVESTMENTS ---
export const INITIAL_INVESTMENTS: Investment[] = [
  {
    id: 'inv1',
    name: 'Vanguard S&P 500 ETF',
    ticker: 'VOO',
    type: 'etf',
    strategy: 'passive',
    quantity: 150,
    costBasis: 55000,
    currentPrice: 412.50,
    currentValue: 61875,
    unrealizedPnL: 6875,
    roiPercent: 12.5,
    currency: 'USD',
    lastUpdated: '2023-10-24'
  },
  {
    id: 'inv2',
    name: 'Tesla Inc',
    ticker: 'TSLA',
    type: 'stock',
    strategy: 'active',
    quantity: 50,
    costBasis: 12000,
    currentPrice: 215.00,
    currentValue: 10750,
    unrealizedPnL: -1250,
    roiPercent: -10.4,
    currency: 'USD',
    lastUpdated: '2023-10-24'
  },
  {
    id: 'inv3',
    name: 'Miami Condo',
    type: 'real_estate',
    strategy: 'passive',
    quantity: 1,
    costBasis: 450000,
    currentPrice: 525000,
    currentValue: 525000,
    unrealizedPnL: 75000,
    roiPercent: 16.6,
    currency: 'USD',
    lastUpdated: '2023-09-01'
  }
];
